"$schema" = "https://conductor.build/schemas/settings.repo.schema.json"

environment_variable_files = [".env"]

[scripts]
setup = "./gradlew --no-daemon build"
run = './gradlew --no-daemon run'
archive = "true"
run_mode = "nonconcurrent"
