syntax = "proto3";

package game.blueprint;

option java_package = "com.game.server.proto";
option csharp_namespace = "Game.Server.Proto";

message CurrencyBlueprint {
  repeated CurrencyItem currency = 1;
}

message CurrencyItem {
  string id = 1;
  repeated string category = 2;
  int32 capacity = 3;
  AutoGenerate generate = 4;
  Schedule schedule = 5;
  string icon = 6; //icon file name

  message AutoGenerate {
    int32 amount = 1;
    int32 time = 2;
    int32 capacity = 3;
  }

  message Schedule {
    int64 start = 1;
    int32 duration = 2;
  }
}
