syntax = "proto3";

package game.app;

option java_package = "com.game.server.proto";
option java_outer_classname = "CommonLoginContract";

message CommonLoginRequestProto {
  string player_id = 1;
  string device_id = 2;
  CommonLoginClientProto client = 3;
}

message CommonLoginClientProto {
  // platform
  //
  // platform
  string platform = 1;

  string identifier = 2;
  string version = 3;

  map<string, string> misc = 5;
}

message CommonLoginResponseProto {
  string asset = 1;
  string odl = 2;
  string odb = 3;
  string device_id = 4;
  string player_id = 5;
  string access_token = 6;
  int64 session_expires_at = 7;
}
