version: "3"
services:
  application:
    image: ${ENV_ECR}:application_${ENV_VERSION}
    build:
      context: ../
      args:
        config_file: application_ecs.conf
      dockerfile: docker/application/Dockerfile
  worker:
    image: ${ENV_ECR}:worker_${ENV_VERSION}
    build:
      context: ../
      args:
        config_file: application_ecs.conf
      dockerfile: docker/worker/Dockerfile